console.log("hello from dom");

console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");

console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
console.log("hello from dom js");
